// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/inventory/internal/repository/model"
	mock "github.com/stretchr/testify/mock"
)

// IPartRepository is an autogenerated mock type for the IPartRepository type
type IPartRepository struct {
	mock.Mock
}

type IPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IPartRepository) EXPECT() *IPartRepository_Expecter {
	return &IPartRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, dto
func (_m *IPartRepository) Create(ctx context.Context, dto model.RepoPart) (string, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RepoPart) (string, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RepoPart) string); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RepoPart) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IPartRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.RepoPart
func (_e *IPartRepository_Expecter) Create(ctx interface{}, dto interface{}) *IPartRepository_Create_Call {
	return &IPartRepository_Create_Call{Call: _e.mock.On("Create", ctx, dto)}
}

func (_c *IPartRepository_Create_Call) Run(run func(ctx context.Context, dto model.RepoPart)) *IPartRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RepoPart))
	})
	return _c
}

func (_c *IPartRepository_Create_Call) Return(_a0 string, _a1 error) *IPartRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_Create_Call) RunAndReturn(run func(context.Context, model.RepoPart) (string, error)) *IPartRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *IPartRepository) Get(ctx context.Context, uuid string) (model.RepoPart, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.RepoPart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.RepoPart, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RepoPart); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.RepoPart)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IPartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *IPartRepository_Expecter) Get(ctx interface{}, uuid interface{}) *IPartRepository_Get_Call {
	return &IPartRepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *IPartRepository_Get_Call) Run(run func(ctx context.Context, uuid string)) *IPartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IPartRepository_Get_Call) Return(_a0 model.RepoPart, _a1 error) *IPartRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.RepoPart, error)) *IPartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, dto
func (_m *IPartRepository) List(ctx context.Context, dto model.RepoPartFilter) ([]model.RepoPart, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.RepoPart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RepoPartFilter) ([]model.RepoPart, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RepoPartFilter) []model.RepoPart); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RepoPart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RepoPartFilter) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type IPartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.RepoPartFilter
func (_e *IPartRepository_Expecter) List(ctx interface{}, dto interface{}) *IPartRepository_List_Call {
	return &IPartRepository_List_Call{Call: _e.mock.On("List", ctx, dto)}
}

func (_c *IPartRepository_List_Call) Run(run func(ctx context.Context, dto model.RepoPartFilter)) *IPartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RepoPartFilter))
	})
	return _c
}

func (_c *IPartRepository_List_Call) Return(_a0 []model.RepoPart, _a1 error) *IPartRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartRepository_List_Call) RunAndReturn(run func(context.Context, model.RepoPartFilter) ([]model.RepoPart, error)) *IPartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPartRepository creates a new instance of IPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartRepository {
	mock := &IPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
