// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/notification/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// INotificationTelegramService is an autogenerated mock type for the INotificationTelegramService type
type INotificationTelegramService struct {
	mock.Mock
}

type INotificationTelegramService_Expecter struct {
	mock *mock.Mock
}

func (_m *INotificationTelegramService) EXPECT() *INotificationTelegramService_Expecter {
	return &INotificationTelegramService_Expecter{mock: &_m.Mock}
}

// SendOrderAssembledNotification provides a mock function with given fields: ctx, dto
func (_m *INotificationTelegramService) SendOrderAssembledNotification(ctx context.Context, dto model.OrderAssembledInEvent) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderAssembledNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderAssembledInEvent) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INotificationTelegramService_SendOrderAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderAssembledNotification'
type INotificationTelegramService_SendOrderAssembledNotification_Call struct {
	*mock.Call
}

// SendOrderAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.OrderAssembledInEvent
func (_e *INotificationTelegramService_Expecter) SendOrderAssembledNotification(ctx interface{}, dto interface{}) *INotificationTelegramService_SendOrderAssembledNotification_Call {
	return &INotificationTelegramService_SendOrderAssembledNotification_Call{Call: _e.mock.On("SendOrderAssembledNotification", ctx, dto)}
}

func (_c *INotificationTelegramService_SendOrderAssembledNotification_Call) Run(run func(ctx context.Context, dto model.OrderAssembledInEvent)) *INotificationTelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderAssembledInEvent))
	})
	return _c
}

func (_c *INotificationTelegramService_SendOrderAssembledNotification_Call) Return(_a0 error) *INotificationTelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INotificationTelegramService_SendOrderAssembledNotification_Call) RunAndReturn(run func(context.Context, model.OrderAssembledInEvent) error) *INotificationTelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendOrderPaidNotification provides a mock function with given fields: ctx, dto
func (_m *INotificationTelegramService) SendOrderPaidNotification(ctx context.Context, dto model.OrderPaidInEvent) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPaidNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidInEvent) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INotificationTelegramService_SendOrderPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPaidNotification'
type INotificationTelegramService_SendOrderPaidNotification_Call struct {
	*mock.Call
}

// SendOrderPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.OrderPaidInEvent
func (_e *INotificationTelegramService_Expecter) SendOrderPaidNotification(ctx interface{}, dto interface{}) *INotificationTelegramService_SendOrderPaidNotification_Call {
	return &INotificationTelegramService_SendOrderPaidNotification_Call{Call: _e.mock.On("SendOrderPaidNotification", ctx, dto)}
}

func (_c *INotificationTelegramService_SendOrderPaidNotification_Call) Run(run func(ctx context.Context, dto model.OrderPaidInEvent)) *INotificationTelegramService_SendOrderPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidInEvent))
	})
	return _c
}

func (_c *INotificationTelegramService_SendOrderPaidNotification_Call) Return(_a0 error) *INotificationTelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INotificationTelegramService_SendOrderPaidNotification_Call) RunAndReturn(run func(context.Context, model.OrderPaidInEvent) error) *INotificationTelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewINotificationTelegramService creates a new instance of INotificationTelegramService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINotificationTelegramService(t interface {
	mock.TestingT
	Cleanup(func())
}) *INotificationTelegramService {
	mock := &INotificationTelegramService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
