// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Artyom099/factory/order/internal/service/model"
)

// IPaymentClient is an autogenerated mock type for the IPaymentClient type
type IPaymentClient struct {
	mock.Mock
}

type IPaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IPaymentClient) EXPECT() *IPaymentClient_Expecter {
	return &IPaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, paymentMethod, orderUUID, userUUID
func (_m *IPaymentClient) PayOrder(ctx context.Context, paymentMethod model.OrderPaymentMethod, orderUUID string, userUUID string) (string, error) {
	ret := _m.Called(ctx, paymentMethod, orderUUID, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaymentMethod, string, string) (string, error)); ok {
		return rf(ctx, paymentMethod, orderUUID, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaymentMethod, string, string) string); ok {
		r0 = rf(ctx, paymentMethod, orderUUID, userUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OrderPaymentMethod, string, string) error); ok {
		r1 = rf(ctx, paymentMethod, orderUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type IPaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod model.OrderPaymentMethod
//   - orderUUID string
//   - userUUID string
func (_e *IPaymentClient_Expecter) PayOrder(ctx interface{}, paymentMethod interface{}, orderUUID interface{}, userUUID interface{}) *IPaymentClient_PayOrder_Call {
	return &IPaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, paymentMethod, orderUUID, userUUID)}
}

func (_c *IPaymentClient_PayOrder_Call) Run(run func(ctx context.Context, paymentMethod model.OrderPaymentMethod, orderUUID string, userUUID string)) *IPaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaymentMethod), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *IPaymentClient_PayOrder_Call) Return(_a0 string, _a1 error) *IPaymentClient_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPaymentClient_PayOrder_Call) RunAndReturn(run func(context.Context, model.OrderPaymentMethod, string, string) (string, error)) *IPaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPaymentClient creates a new instance of IPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPaymentClient {
	mock := &IPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
