with-expecter: true
# boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

# команда для генерации моков - task test:mockery:gen

packages:
  # payment
  github.com/Artyom099/factory/payment/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Artyom099/factory/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Artyom099/factory/payment/internal/repository:
    config:
      include-regex: ".*Repository"

  # inventory
  github.com/Artyom099/factory/inventory/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Artyom099/factory/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Artyom099/factory/inventory/internal/repository:
    config:
      include-regex: ".*Repository"

  # order
  github.com/Artyom099/factory/order/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Artyom099/factory/order/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Artyom099/factory/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/Artyom099/factory/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  # assembly
  github.com/Artyom099/factory/assembly/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Artyom099/factory/assembly/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Artyom099/factory/assembly/internal/repository:
    config:
      include-regex: ".*Repository"

  # notification
  github.com/Artyom099/factory/notification/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Artyom099/factory/notification/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Artyom099/factory/notification/internal/repository:
    config:
      include-regex: ".*Repository"

  # iam
  github.com/Artyom099/factory/iam/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Artyom099/factory/iam/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Artyom099/factory/iam/internal/repository:
    config:
      include-regex: ".*Repository"
