version: "3"

includes:
  lint: ./taskfiles/lint.yml
  test: ./taskfiles/test.yml
  env: ./taskfiles/env.yml
  run: ./taskfiles/run.yml
  rest: ./taskfiles/rest.yml
  proto: ./taskfiles/proto.yml
  docker: ./taskfiles/docker.yml
  coverage: ./taskfiles/coverage.yml
  migration: ./taskfiles/migration.yml

# Глобальные переменные проекта
vars:
  GO_VERSION: "1.24"
  GOLANGCI_LINT_VERSION: "v2.1.5"
  GCI_VERSION: "v0.13.6"
  GOFUMPT_VERSION: "v0.8.0"
  BUF_VERSION: "1.53.0"
  PROTOC_GEN_GO_VERSION: "v1.36.6"
  PROTOC_GEN_GO_GRPC_VERSION: "v1.5.1"
  PROTOC_GEN_VALIDATE_VERSION: "v1.2.1"
  OGEN_VERSION: "v1.12.0"
  YQ_VERSION: "v4.45.2"
  GRPCURL_VERSION: "v1.9.3"
  MOCKERY_VERSION: "v2.53.3"
  GOOSE_VERSION: "v3.26.0"
  ENVSUBST_VERSION: "v1.4.3"

  BIN_DIR: "{{.ROOT_DIR}}/bin"
  GOLANGCI_LINT: "{{.BIN_DIR}}/golangci-lint"
  GCI: "{{.BIN_DIR}}/gci"
  GOFUMPT: "{{.BIN_DIR}}/gofumpt"
  BUF: "{{.BIN_DIR}}/buf"
  OGEN: "{{.BIN_DIR}}/ogen"
  YQ: "{{.BIN_DIR}}/yq"
  PROTOC_GEN_GO: "{{.BIN_DIR}}/protoc-gen-go"
  PROTOC_GEN_GO_GRPC: "{{.BIN_DIR}}/protoc-gen-go-grpc"
  PROTOC_GEN_VALIDATE: "{{.BIN_DIR}}/protoc-gen-validate"
  GRPCURL: "{{.BIN_DIR}}/grpcurl"
  MOCKERY: "{{.BIN_DIR}}/mockery"
  GOOSE: "{{.BIN_DIR}}/goose"
  ENVSUBST: "{{.BIN_DIR}}/envsubst"
  ENVDIR: "{{.ROOT_DIR}}/deploy/env"

  NODE_MODULES_DIR: "{{.ROOT_DIR}}/node_modules/.bin"
  REDOCLY: "{{.NODE_MODULES_DIR}}/redocly"

  OPEN_API_ORDER_V1_BASE: "{{.ROOT_DIR}}/shared/api/order/v1/order.openapi.yaml"
  OPEN_API_ORDER_V1_BUNDLE: "{{.ROOT_DIR}}/shared/api/bundles/order.openapi.v1.bundle.yaml"

  OPEN_API_FILES: "{{.ROOT_DIR}}/shared/api/bundles"

  COVERAGE_DIR: "{{.ROOT_DIR}}/coverage"
  COVERAGE_FILE: total.out

  GIST_ID: "8f1426178499e4bfc15735575c432973"

  SERVICES: order,inventory,payment,assembly,notification,core,iam
  MODULES: inventory order payment iam
  LINT_MODULES: inventory order payment shared platform assembly notification iam

tasks:
  deps:update:
    desc: "Обновление зависимостей в go.mod во всех модулях"
    cmds:
      - |
        echo "🔄 Обновление зависимостей в go.mod во всех модулях"
        for mod in {{.LINT_MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔄 Обновление зависимостей в $mod"
            (cd "$mod" && go mod tidy -compat=1.24) || exit 1
          fi
        done

  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.

      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci, исключая mocks"
    summary: |
      Форматирует все Go-файлы проекта с использованием gofumpt для стандартизации кода
      и gci для сортировки импортов, исключая файлы в директориях mocks.

      Использует инструменты:
        - gofumpt: для стандартизации форматирования
        - gci: для сортировки импортов по стандартным группам
    deps: [install-formatters]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."

        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🧼 Форматируем $module"
            find $module -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
          fi
        done
      - |
        echo "🎯 Сортируем импорты через gci ..."

        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🎯 Сортируем импорты в $module"
            find $module -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/olezhek28/microservices-course-olezhek-solution)" {} +
          fi
        done
