// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TelegramConfig is an autogenerated mock type for the TelegramConfig type
type TelegramConfig struct {
	mock.Mock
}

type TelegramConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramConfig) EXPECT() *TelegramConfig_Expecter {
	return &TelegramConfig_Expecter{mock: &_m.Mock}
}

// ChatID provides a mock function with no fields
func (_m *TelegramConfig) ChatID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// TelegramConfig_ChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatID'
type TelegramConfig_ChatID_Call struct {
	*mock.Call
}

// ChatID is a helper method to define mock.On call
func (_e *TelegramConfig_Expecter) ChatID() *TelegramConfig_ChatID_Call {
	return &TelegramConfig_ChatID_Call{Call: _e.mock.On("ChatID")}
}

func (_c *TelegramConfig_ChatID_Call) Run(run func()) *TelegramConfig_ChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramConfig_ChatID_Call) Return(_a0 int64) *TelegramConfig_ChatID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramConfig_ChatID_Call) RunAndReturn(run func() int64) *TelegramConfig_ChatID_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function with no fields
func (_m *TelegramConfig) Token() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TelegramConfig_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type TelegramConfig_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *TelegramConfig_Expecter) Token() *TelegramConfig_Token_Call {
	return &TelegramConfig_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *TelegramConfig_Token_Call) Run(run func()) *TelegramConfig_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramConfig_Token_Call) Return(_a0 string) *TelegramConfig_Token_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramConfig_Token_Call) RunAndReturn(run func() string) *TelegramConfig_Token_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramConfig creates a new instance of TelegramConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramConfig {
	mock := &TelegramConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
