// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

type IUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserService) EXPECT() *IUserService_Expecter {
	return &IUserService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *IUserService) Get(ctx context.Context, uuid string) (model.User, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IUserService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *IUserService_Expecter) Get(ctx interface{}, uuid interface{}) *IUserService_Get_Call {
	return &IUserService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *IUserService_Get_Call) Run(run func(ctx context.Context, uuid string)) *IUserService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IUserService_Get_Call) Return(_a0 model.User, _a1 error) *IUserService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserService_Get_Call) RunAndReturn(run func(context.Context, string) (model.User, error)) *IUserService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, user
func (_m *IUserService) Register(ctx context.Context, user model.User) (string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *IUserService_Expecter) Register(ctx interface{}, user interface{}) *IUserService_Register_Call {
	return &IUserService_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *IUserService_Register_Call) Run(run func(ctx context.Context, user model.User)) *IUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *IUserService_Register_Call) Return(_a0 string, _a1 error) *IUserService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserService_Register_Call) RunAndReturn(run func(context.Context, model.User) (string, error)) *IUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
