// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

type IAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *IAuthService) EXPECT() *IAuthService_Expecter {
	return &IAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, login, password
func (_m *IAuthService) Login(ctx context.Context, login string, password string) (string, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type IAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *IAuthService_Expecter) Login(ctx interface{}, login interface{}, password interface{}) *IAuthService_Login_Call {
	return &IAuthService_Login_Call{Call: _e.mock.On("Login", ctx, login, password)}
}

func (_c *IAuthService_Login_Call) Run(run func(ctx context.Context, login string, password string)) *IAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IAuthService_Login_Call) Return(_a0 string, _a1 error) *IAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *IAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function with given fields: ctx, sessionUuid
func (_m *IAuthService) Whoami(ctx context.Context, sessionUuid string) (model.User, model.Session, error) {
	ret := _m.Called(ctx, sessionUuid)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 model.User
	var r1 model.Session
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.User, model.Session, error)); ok {
		return rf(ctx, sessionUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, sessionUuid)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) model.Session); ok {
		r1 = rf(ctx, sessionUuid)
	} else {
		r1 = ret.Get(1).(model.Session)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, sessionUuid)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IAuthService_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type IAuthService_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUuid string
func (_e *IAuthService_Expecter) Whoami(ctx interface{}, sessionUuid interface{}) *IAuthService_Whoami_Call {
	return &IAuthService_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUuid)}
}

func (_c *IAuthService_Whoami_Call) Run(run func(ctx context.Context, sessionUuid string)) *IAuthService_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IAuthService_Whoami_Call) Return(_a0 model.User, _a1 model.Session, _a2 error) *IAuthService_Whoami_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IAuthService_Whoami_Call) RunAndReturn(run func(context.Context, string) (model.User, model.Session, error)) *IAuthService_Whoami_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAuthService creates a new instance of IAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthService {
	mock := &IAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
