// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAssemblyProducerService is an autogenerated mock type for the IAssemblyProducerService type
type IAssemblyProducerService struct {
	mock.Mock
}

type IAssemblyProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *IAssemblyProducerService) EXPECT() *IAssemblyProducerService_Expecter {
	return &IAssemblyProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderAssembled provides a mock function with given fields: ctx, event
func (_m *IAssemblyProducerService) ProduceOrderAssembled(ctx context.Context, event model.ShipAssembledOutEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderAssembled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledOutEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IAssemblyProducerService_ProduceOrderAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderAssembled'
type IAssemblyProducerService_ProduceOrderAssembled_Call struct {
	*mock.Call
}

// ProduceOrderAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledOutEvent
func (_e *IAssemblyProducerService_Expecter) ProduceOrderAssembled(ctx interface{}, event interface{}) *IAssemblyProducerService_ProduceOrderAssembled_Call {
	return &IAssemblyProducerService_ProduceOrderAssembled_Call{Call: _e.mock.On("ProduceOrderAssembled", ctx, event)}
}

func (_c *IAssemblyProducerService_ProduceOrderAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledOutEvent)) *IAssemblyProducerService_ProduceOrderAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledOutEvent))
	})
	return _c
}

func (_c *IAssemblyProducerService_ProduceOrderAssembled_Call) Return(_a0 error) *IAssemblyProducerService_ProduceOrderAssembled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAssemblyProducerService_ProduceOrderAssembled_Call) RunAndReturn(run func(context.Context, model.ShipAssembledOutEvent) error) *IAssemblyProducerService_ProduceOrderAssembled_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAssemblyProducerService creates a new instance of IAssemblyProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAssemblyProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAssemblyProducerService {
	mock := &IAssemblyProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
