// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAssemblyService is an autogenerated mock type for the IAssemblyService type
type IAssemblyService struct {
	mock.Mock
}

type IAssemblyService_Expecter struct {
	mock *mock.Mock
}

func (_m *IAssemblyService) EXPECT() *IAssemblyService_Expecter {
	return &IAssemblyService_Expecter{mock: &_m.Mock}
}

// Assembly provides a mock function with given fields: ctx, dto
func (_m *IAssemblyService) Assembly(ctx context.Context, dto model.OrderPaidInEvent) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Assembly")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidInEvent) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IAssemblyService_Assembly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assembly'
type IAssemblyService_Assembly_Call struct {
	*mock.Call
}

// Assembly is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.OrderPaidInEvent
func (_e *IAssemblyService_Expecter) Assembly(ctx interface{}, dto interface{}) *IAssemblyService_Assembly_Call {
	return &IAssemblyService_Assembly_Call{Call: _e.mock.On("Assembly", ctx, dto)}
}

func (_c *IAssemblyService_Assembly_Call) Run(run func(ctx context.Context, dto model.OrderPaidInEvent)) *IAssemblyService_Assembly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidInEvent))
	})
	return _c
}

func (_c *IAssemblyService_Assembly_Call) Return(_a0 error) *IAssemblyService_Assembly_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAssemblyService_Assembly_Call) RunAndReturn(run func(context.Context, model.OrderPaidInEvent) error) *IAssemblyService_Assembly_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAssemblyService creates a new instance of IAssemblyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAssemblyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAssemblyService {
	mock := &IAssemblyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
