// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: events/v1/order.proto

package events_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _order_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on OrderPaidEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderPaidEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPaidEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderPaidEventMultiError,
// or nil if none found.
func (m *OrderPaidEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPaidEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetEventUuid()); err != nil {
		err = OrderPaidEventValidationError{
			field:  "EventUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetOrderUuid()); err != nil {
		err = OrderPaidEventValidationError{
			field:  "OrderUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserUuid()); err != nil {
		err = OrderPaidEventValidationError{
			field:  "UserUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := PaymentMethod_name[int32(m.GetPaymentMethod())]; !ok {
		err := OrderPaidEventValidationError{
			field:  "PaymentMethod",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetTransactionUuid()); err != nil {
		err = OrderPaidEventValidationError{
			field:  "TransactionUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderPaidEventMultiError(errors)
	}

	return nil
}

func (m *OrderPaidEvent) _validateUuid(uuid string) error {
	if matched := _order_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderPaidEventMultiError is an error wrapping multiple validation errors
// returned by OrderPaidEvent.ValidateAll() if the designated constraints
// aren't met.
type OrderPaidEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPaidEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPaidEventMultiError) AllErrors() []error { return m }

// OrderPaidEventValidationError is the validation error returned by
// OrderPaidEvent.Validate if the designated constraints aren't met.
type OrderPaidEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPaidEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPaidEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPaidEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPaidEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPaidEventValidationError) ErrorName() string { return "OrderPaidEventValidationError" }

// Error satisfies the builtin error interface
func (e OrderPaidEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPaidEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPaidEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPaidEventValidationError{}

// Validate checks the field values on OrderAssembledEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderAssembledEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderAssembledEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderAssembledEventMultiError, or nil if none found.
func (m *OrderAssembledEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderAssembledEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetEventUuid()); err != nil {
		err = OrderAssembledEventValidationError{
			field:  "EventUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetOrderUuid()); err != nil {
		err = OrderAssembledEventValidationError{
			field:  "OrderUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserUuid()); err != nil {
		err = OrderAssembledEventValidationError{
			field:  "UserUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for BuildTimeSec

	if len(errors) > 0 {
		return OrderAssembledEventMultiError(errors)
	}

	return nil
}

func (m *OrderAssembledEvent) _validateUuid(uuid string) error {
	if matched := _order_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderAssembledEventMultiError is an error wrapping multiple validation
// errors returned by OrderAssembledEvent.ValidateAll() if the designated
// constraints aren't met.
type OrderAssembledEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderAssembledEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderAssembledEventMultiError) AllErrors() []error { return m }

// OrderAssembledEventValidationError is the validation error returned by
// OrderAssembledEvent.Validate if the designated constraints aren't met.
type OrderAssembledEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderAssembledEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderAssembledEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderAssembledEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderAssembledEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderAssembledEventValidationError) ErrorName() string {
	return "OrderAssembledEventValidationError"
}

// Error satisfies the builtin error interface
func (e OrderAssembledEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderAssembledEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderAssembledEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderAssembledEventValidationError{}
