// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/iam/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ISessionRepository is an autogenerated mock type for the ISessionRepository type
type ISessionRepository struct {
	mock.Mock
}

type ISessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ISessionRepository) EXPECT() *ISessionRepository_Expecter {
	return &ISessionRepository_Expecter{mock: &_m.Mock}
}

// AddSessionToUserSet provides a mock function with given fields: ctx, userID, sessionID
func (_m *ISessionRepository) AddSessionToUserSet(ctx context.Context, userID string, sessionID string) error {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for AddSessionToUserSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISessionRepository_AddSessionToUserSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSessionToUserSet'
type ISessionRepository_AddSessionToUserSet_Call struct {
	*mock.Call
}

// AddSessionToUserSet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *ISessionRepository_Expecter) AddSessionToUserSet(ctx interface{}, userID interface{}, sessionID interface{}) *ISessionRepository_AddSessionToUserSet_Call {
	return &ISessionRepository_AddSessionToUserSet_Call{Call: _e.mock.On("AddSessionToUserSet", ctx, userID, sessionID)}
}

func (_c *ISessionRepository_AddSessionToUserSet_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *ISessionRepository_AddSessionToUserSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ISessionRepository_AddSessionToUserSet_Call) Return(_a0 error) *ISessionRepository_AddSessionToUserSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISessionRepository_AddSessionToUserSet_Call) RunAndReturn(run func(context.Context, string, string) error) *ISessionRepository_AddSessionToUserSet_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, session, ttl
func (_m *ISessionRepository) Create(ctx context.Context, session model.Session, ttl time.Duration) error {
	ret := _m.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Session, time.Duration) error); ok {
		r0 = rf(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ISessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session model.Session
//   - ttl time.Duration
func (_e *ISessionRepository_Expecter) Create(ctx interface{}, session interface{}, ttl interface{}) *ISessionRepository_Create_Call {
	return &ISessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session, ttl)}
}

func (_c *ISessionRepository_Create_Call) Run(run func(ctx context.Context, session model.Session, ttl time.Duration)) *ISessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Session), args[2].(time.Duration))
	})
	return _c
}

func (_c *ISessionRepository_Create_Call) Return(_a0 error) *ISessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISessionRepository_Create_Call) RunAndReturn(run func(context.Context, model.Session, time.Duration) error) *ISessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, sessionUUID
func (_m *ISessionRepository) Get(ctx context.Context, sessionUUID string) (model.Session, error) {
	ret := _m.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Session, error)); ok {
		return rf(ctx, sessionUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Session); ok {
		r0 = rf(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ISessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID string
func (_e *ISessionRepository_Expecter) Get(ctx interface{}, sessionUUID interface{}) *ISessionRepository_Get_Call {
	return &ISessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, sessionUUID)}
}

func (_c *ISessionRepository_Get_Call) Run(run func(ctx context.Context, sessionUUID string)) *ISessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISessionRepository_Get_Call) Return(_a0 model.Session, _a1 error) *ISessionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISessionRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Session, error)) *ISessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewISessionRepository creates a new instance of ISessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISessionRepository {
	mock := &ISessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
