// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PaymentClientConfig is an autogenerated mock type for the PaymentClientConfig type
type PaymentClientConfig struct {
	mock.Mock
}

type PaymentClientConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClientConfig) EXPECT() *PaymentClientConfig_Expecter {
	return &PaymentClientConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *PaymentClientConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PaymentClientConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type PaymentClientConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *PaymentClientConfig_Expecter) Address() *PaymentClientConfig_Address_Call {
	return &PaymentClientConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *PaymentClientConfig_Address_Call) Run(run func()) *PaymentClientConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PaymentClientConfig_Address_Call) Return(_a0 string) *PaymentClientConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentClientConfig_Address_Call) RunAndReturn(run func() string) *PaymentClientConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClientConfig creates a new instance of PaymentClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClientConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClientConfig {
	mock := &PaymentClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
