// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/inventory/internal/service/model"
	mock "github.com/stretchr/testify/mock"
)

// IPartService is an autogenerated mock type for the IPartService type
type IPartService struct {
	mock.Mock
}

type IPartService_Expecter struct {
	mock *mock.Mock
}

func (_m *IPartService) EXPECT() *IPartService_Expecter {
	return &IPartService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, dto
func (_m *IPartService) Create(ctx context.Context, dto model.Part) (string, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Part) (string, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Part) string); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Part) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IPartService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.Part
func (_e *IPartService_Expecter) Create(ctx interface{}, dto interface{}) *IPartService_Create_Call {
	return &IPartService_Create_Call{Call: _e.mock.On("Create", ctx, dto)}
}

func (_c *IPartService_Create_Call) Run(run func(ctx context.Context, dto model.Part)) *IPartService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Part))
	})
	return _c
}

func (_c *IPartService_Create_Call) Return(_a0 string, _a1 error) *IPartService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartService_Create_Call) RunAndReturn(run func(context.Context, model.Part) (string, error)) *IPartService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *IPartService) Get(ctx context.Context, uuid string) (model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IPartService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *IPartService_Expecter) Get(ctx interface{}, uuid interface{}) *IPartService_Get_Call {
	return &IPartService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *IPartService_Get_Call) Run(run func(ctx context.Context, uuid string)) *IPartService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IPartService_Get_Call) Return(_a0 model.Part, _a1 error) *IPartService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Part, error)) *IPartService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, dto
func (_m *IPartService) List(ctx context.Context, dto model.PartFilter) ([]model.Part, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartFilter) ([]model.Part, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartFilter) []model.Part); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartFilter) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPartService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type IPartService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.PartFilter
func (_e *IPartService_Expecter) List(ctx interface{}, dto interface{}) *IPartService_List_Call {
	return &IPartService_List_Call{Call: _e.mock.On("List", ctx, dto)}
}

func (_c *IPartService_List_Call) Run(run func(ctx context.Context, dto model.PartFilter)) *IPartService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartFilter))
	})
	return _c
}

func (_c *IPartService_List_Call) Return(_a0 []model.Part, _a1 error) *IPartService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPartService_List_Call) RunAndReturn(run func(context.Context, model.PartFilter) ([]model.Part, error)) *IPartService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPartService creates a new instance of IPartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartService {
	mock := &IPartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
