// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AssemblyGRPCConfig is an autogenerated mock type for the AssemblyGRPCConfig type
type AssemblyGRPCConfig struct {
	mock.Mock
}

type AssemblyGRPCConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyGRPCConfig) EXPECT() *AssemblyGRPCConfig_Expecter {
	return &AssemblyGRPCConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *AssemblyGRPCConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AssemblyGRPCConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type AssemblyGRPCConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *AssemblyGRPCConfig_Expecter) Address() *AssemblyGRPCConfig_Address_Call {
	return &AssemblyGRPCConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *AssemblyGRPCConfig_Address_Call) Run(run func()) *AssemblyGRPCConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AssemblyGRPCConfig_Address_Call) Return(_a0 string) *AssemblyGRPCConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyGRPCConfig_Address_Call) RunAndReturn(run func() string) *AssemblyGRPCConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// NewAssemblyGRPCConfig creates a new instance of AssemblyGRPCConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyGRPCConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyGRPCConfig {
	mock := &AssemblyGRPCConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
