// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/payment/internal/service/model"
	mock "github.com/stretchr/testify/mock"
)

// IPaymentRepository is an autogenerated mock type for the IPaymentRepository type
type IPaymentRepository struct {
	mock.Mock
}

type IPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IPaymentRepository) EXPECT() *IPaymentRepository_Expecter {
	return &IPaymentRepository_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, dto
func (_m *IPaymentRepository) PayOrder(ctx context.Context, dto model.Payment) (string, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Payment) (string, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Payment) string); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Payment) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPaymentRepository_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type IPaymentRepository_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.Payment
func (_e *IPaymentRepository_Expecter) PayOrder(ctx interface{}, dto interface{}) *IPaymentRepository_PayOrder_Call {
	return &IPaymentRepository_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, dto)}
}

func (_c *IPaymentRepository_PayOrder_Call) Run(run func(ctx context.Context, dto model.Payment)) *IPaymentRepository_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Payment))
	})
	return _c
}

func (_c *IPaymentRepository_PayOrder_Call) Return(_a0 string, _a1 error) *IPaymentRepository_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPaymentRepository_PayOrder_Call) RunAndReturn(run func(context.Context, model.Payment) (string, error)) *IPaymentRepository_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPaymentRepository creates a new instance of IPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPaymentRepository {
	mock := &IPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
