// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Artyom099/factory/order/internal/service/model"
	mock "github.com/stretchr/testify/mock"
)

// IProducerService is an autogenerated mock type for the IProducerService type
type IProducerService struct {
	mock.Mock
}

type IProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *IProducerService) EXPECT() *IProducerService_Expecter {
	return &IProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderPaid provides a mock function with given fields: ctx, event
func (_m *IProducerService) ProduceOrderPaid(ctx context.Context, event model.OrderPaidOutEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidOutEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IProducerService_ProduceOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderPaid'
type IProducerService_ProduceOrderPaid_Call struct {
	*mock.Call
}

// ProduceOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidOutEvent
func (_e *IProducerService_Expecter) ProduceOrderPaid(ctx interface{}, event interface{}) *IProducerService_ProduceOrderPaid_Call {
	return &IProducerService_ProduceOrderPaid_Call{Call: _e.mock.On("ProduceOrderPaid", ctx, event)}
}

func (_c *IProducerService_ProduceOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaidOutEvent)) *IProducerService_ProduceOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidOutEvent))
	})
	return _c
}

func (_c *IProducerService_ProduceOrderPaid_Call) Return(_a0 error) *IProducerService_ProduceOrderPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IProducerService_ProduceOrderPaid_Call) RunAndReturn(run func(context.Context, model.OrderPaidOutEvent) error) *IProducerService_ProduceOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewIProducerService creates a new instance of IProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProducerService {
	mock := &IProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
