name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  extract-vars:
    name: Extract Variables from Taskfile
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract.outputs.GO_VERSION }}
      golangci-lint-version: ${{ steps.extract.outputs.GOLANGCI_LINT_VERSION }}
      modules: ${{ steps.extract.outputs.MODULES }}
      gist-id: ${{ steps.extract.outputs.GIST_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Extract variables from Taskfile
        id: extract
        run: |
          chmod +x .github/scripts/extract-versions.sh
          .github/scripts/extract-versions.sh

  lint:
    needs: extract-vars
    uses: ./.github/workflows/lint-reusable.yml
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}
      golangci-lint-version: ${{ needs.extract-vars.outputs.golangci-lint-version }}

  test:
    needs: lint
    uses: ./.github/workflows/test-reusable.yml
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}

  coverage:
    needs: test
    uses: ./.github/workflows/test-coverage-reusable.yml
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}
      gist-id: ${{ needs.extract-vars.outputs.gist-id }}
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
